[project]
name = "shiny_router"
version = "0.1.15"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas",
    "shiny",
    "shiny-router",
    "pytest",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"shiny_router" = ["www/*"]

[tool.uv.sources]
shiny-router = { workspace = true }
